version: "3"
services:
  app:
    build:
      context: ./docker/php
      args:
      - TZ=${TZ}
    ports:
    - ${APP_PORT}:8000
    volumes:
    - ${PROJECT_PATH}:/work
    - ./docker/ash:/etc/profile.d
    - ./docker/php/psysh:/root/.config/psysh
    - ./logs:/var/log/php
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment:
    - DB_CONNECTION=pgsql
    - DB_HOST=db
    - DB_DATABASE=${DB_NAME}
    - DB_PORT=${POSTGRES_PORT}
    - DB_USERNAME=${DB_USER}
    - DB_PASSWORD=${DB_PASS}
    - TZ=${TZ}
    - MAIL_HOST=${MAIL_HOST}
    - MAIL_PORT=${MAIL_PORT}
    - CACHE_DRIVER=redis
    - SESSION_DRIVER=redis
    - QUEUE_DRIVER=redis
    - REDIS_HOST=redis

  web:
    image: nginx:1.17-alpine
    depends_on:
    - app
    ports:
    - ${WEB_PORT}:80
    volumes:
    - ${PROJECT_PATH}:/work
    - ./logs:/var/log/nginx
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
    - TZ=${TZ}

  db:
    image: postgres:12
    ports:
     - ${DB_PORT}:${POSTGRES_PORT}
    volumes:
     - db-store:/var/lib/postgresql/data
     - ./logs:/var/log/postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_ROOT_PASSWORD: ${DB_PASS}
      TZ: ${TZ}

  node:
    image: node:12.13-alpine
    tty: true
    volumes:
    - ${PROJECT_PATH}:/work
    working_dir: /work

  redis:
    image: redis:5.0-alpine
    volumes:
    - redis-store:/data

volumes:
  db-store:
  redis-store:
